"""Add maintenance_level to work_orders and arsenal_repair_tasks

Revision ID: 082a1e7c482a
Revises: 20260613_0011
Create Date: 2026-06-15 14:41:29.028916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082a1e7c482a'
down_revision: Union[str, None] = '20260613_0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arsenal_component_receptions', sa.Column('failure_report_code', sa.String(length=120), nullable=True))
    op.add_column('arsenal_component_receptions', sa.Column('maintenance_action_form_code', sa.String(length=120), nullable=True))
    op.add_column('arsenal_component_receptions', sa.Column('work_order_code', sa.String(length=120), nullable=True))
    
    # Create enum type first for Postgres
    repair_level_enum = sa.Enum('O_LEVEL', 'I_LEVEL', 'D_LEVEL', name='repair_maintenance_level')
    repair_level_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('arsenal_repair_tasks', sa.Column('maintenance_level', repair_level_enum, server_default='I_LEVEL', nullable=False))
    
    op.add_column('arsenal_service_releases', sa.Column('service_release_certificate_code', sa.String(length=120), nullable=True))
    op.add_column('arsenal_service_releases', sa.Column('historical_record_book_code', sa.String(length=120), nullable=True))
    
    main_level_enum = sa.Enum('O_LEVEL', 'I_LEVEL', 'D_LEVEL', name='maintenance_level')
    main_level_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('work_orders', sa.Column('maintenance_level', main_level_enum, server_default='O_LEVEL', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'maintenance_level')
    op.drop_column('arsenal_service_releases', 'historical_record_book_code')
    op.drop_column('arsenal_service_releases', 'service_release_certificate_code')
    op.drop_column('arsenal_repair_tasks', 'maintenance_level')
    op.drop_column('arsenal_component_receptions', 'work_order_code')
    op.drop_column('arsenal_component_receptions', 'maintenance_action_form_code')
    op.drop_column('arsenal_component_receptions', 'failure_report_code')
    # ### end Alembic commands ###
