"""Add SystemUser model and update UserAssignment

Revision ID: 0d1d273bb2b3
Revises: 082a1e7c482a
Create Date: 2026-06-15 15:01:57.641827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1d273bb2b3'
down_revision: Union[str, None] = '082a1e7c482a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_users',
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_users_username'), 'system_users', ['username'], unique=True)
    op.alter_column('arsenal_service_releases', 'service_release_certificate_code',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('arsenal_service_releases', 'historical_record_book_code',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.create_foreign_key(None, 'user_assignments', 'system_users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_assignments', type_='foreignkey')
    op.alter_column('arsenal_service_releases', 'historical_record_book_code',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('arsenal_service_releases', 'service_release_certificate_code',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_index(op.f('ix_system_users_username'), table_name='system_users')
    op.drop_table('system_users')
    # ### end Alembic commands ###
