"""Add logistics inspection to procurement

Revision ID: 18027065ee3c
Revises: 0d1d273bb2b3
Create Date: 2026-06-15 16:43:12.949915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18027065ee3c'
down_revision: Union[str, None] = '0d1d273bb2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supply_chain_procurement_quality_checks', sa.Column('supplier_verified', sa.Boolean(), nullable=False))
    op.add_column('supply_chain_procurement_quality_checks', sa.Column('po_validated', sa.Boolean(), nullable=False))
    op.add_column('supply_chain_procurement_quality_checks', sa.Column('pn_validated', sa.Boolean(), nullable=False))
    op.add_column('supply_chain_procurement_quality_checks', sa.Column('sn_validated', sa.Boolean(), nullable=False))
    op.add_column('supply_chain_procurement_quality_checks', sa.Column('coc_attached', sa.Boolean(), nullable=False))
    op.add_column('supply_chain_procurement_quality_checks', sa.Column('mfg_cert_attached', sa.Boolean(), nullable=False))
    op.add_column('supply_chain_procurement_quality_checks', sa.Column('packaging_inspected', sa.Boolean(), nullable=False))
    op.add_column('supply_chain_procurement_quality_checks', sa.Column('shelf_life_verified', sa.Boolean(), nullable=False))
    op.add_column('supply_chain_procurement_quality_checks', sa.Column('batch_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supply_chain_procurement_quality_checks', 'batch_verified')
    op.drop_column('supply_chain_procurement_quality_checks', 'shelf_life_verified')
    op.drop_column('supply_chain_procurement_quality_checks', 'packaging_inspected')
    op.drop_column('supply_chain_procurement_quality_checks', 'mfg_cert_attached')
    op.drop_column('supply_chain_procurement_quality_checks', 'coc_attached')
    op.drop_column('supply_chain_procurement_quality_checks', 'sn_validated')
    op.drop_column('supply_chain_procurement_quality_checks', 'pn_validated')
    op.drop_column('supply_chain_procurement_quality_checks', 'po_validated')
    op.drop_column('supply_chain_procurement_quality_checks', 'supplier_verified')
    # ### end Alembic commands ###
