"""Add global engine fields to Asset

Revision ID: 1ff40c1615f9
Revises: 18027065ee3c
Create Date: 2026-06-15 18:04:30.840444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff40c1615f9'
down_revision: Union[str, None] = '18027065ee3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('organization_owner_id', sa.UUID(), nullable=True))
    op.add_column('assets', sa.Column('current_location', sa.String(length=200), nullable=True))
    airworthiness_status_enum = sa.Enum('AIRWORTHY', 'NON_AIRWORTHY', 'RESTRICTED', 'AWAITING_CERTIFICATION', 'UNKNOWN', name='airworthiness_status')
    airworthiness_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('assets', sa.Column('airworthiness_status', airworthiness_status_enum, nullable=False, server_default='UNKNOWN'))
    op.create_index(op.f('ix_assets_organization_owner_id'), 'assets', ['organization_owner_id'], unique=False)
    op.create_foreign_key(None, 'assets', 'organizations', ['organization_owner_id'], ['id'])
    op.add_column('document_management_compliance_checks', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.drop_column('document_management_compliance_checks', 'failure_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_management_compliance_checks', sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('document_management_compliance_checks', 'metadata_json')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_organization_owner_id'), table_name='assets')
    op.drop_column('assets', 'airworthiness_status')
    op.drop_column('assets', 'current_location')
    op.drop_column('assets', 'organization_owner_id')
    # ### end Alembic commands ###
