"""Add auditing domain

Revision ID: 4d83724a95db
Revises: 1ff40c1615f9
Create Date: 2026-06-15 18:27:10.429466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d83724a95db'
down_revision: Union[str, None] = '1ff40c1615f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditing_audit_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('origin_terminal', sa.String(length=200), nullable=True),
    sa.Column('document_reference', sa.String(length=120), nullable=True),
    sa.Column('old_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditing_audit_events_action'), 'auditing_audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_auditing_audit_events_entity_id'), 'auditing_audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_auditing_audit_events_entity_type'), 'auditing_audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_auditing_audit_events_timestamp'), 'auditing_audit_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_auditing_audit_events_user_id'), 'auditing_audit_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditing_audit_events_user_id'), table_name='auditing_audit_events')
    op.drop_index(op.f('ix_auditing_audit_events_timestamp'), table_name='auditing_audit_events')
    op.drop_index(op.f('ix_auditing_audit_events_entity_type'), table_name='auditing_audit_events')
    op.drop_index(op.f('ix_auditing_audit_events_entity_id'), table_name='auditing_audit_events')
    op.drop_index(op.f('ix_auditing_audit_events_action'), table_name='auditing_audit_events')
    op.drop_table('auditing_audit_events')
    # ### end Alembic commands ###
