"""Add asset commissioning states

Revision ID: f65212a651fa
Revises: 4d83724a95db
Create Date: 2026-06-15 18:42:49.917128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65212a651fa'
down_revision: Union[str, None] = '4d83724a95db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE asset_status ADD VALUE IF NOT EXISTS 'PENDING_COMMISSIONING'")
    op.execute("ALTER TYPE asset_status ADD VALUE IF NOT EXISTS 'UNDER_INSPECTION'")
    op.execute("ALTER TYPE asset_status ADD VALUE IF NOT EXISTS 'ACTIVE_SERVICE'")
    op.execute("ALTER TYPE asset_status ADD VALUE IF NOT EXISTS 'QUARANTINED'")
    op.execute("ALTER TYPE asset_status ADD VALUE IF NOT EXISTS 'STORAGE'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
